---
- name: check lvm configured
  stat:
    path: "/.lvm.done"
  tags:
    - config.lvm
  register: lvm_configured


- name: create ledger mount point
  file:
    path: "{{ ledger_path }}"
    state: directory
    mode: '0755'
  tags:
    - config.lvm

- name: configured lvm
  block:
    - name: set lvm configured
      file:
        path: "/.lvm.done"
        state: touch

    - name: Add solana lvm
      lvol:
        vg: "{{ lvm_vg }}"
        lv: swap
        size: "{{ (swap_file_size_gb | int + 5) | int }}G"
        state: present

    - name: Create a ext4 filesystem on swap dir
      filesystem:
        fstype: ext4
        dev: "/dev/{{ lvm_vg }}/swap"

    - name: Create swap dir mount point
      file:
        path: "/mnt/swap"
        state: directory
        mode: '0755'

    - name: Write swap dir entry in fstab
      ansible.posix.mount:
        path: "/mnt/swap"
        src: "/dev/{{ lvm_vg }}/swap"
        fstype: ext4
        state: mounted

    - name: Add solana lvm
      lvol:
        vg: "{{ lvm_vg }}"
        lv: ledger
        size: 100%FREE
        state: present

    - name: Create a ext4 filesystem on ledger
      filesystem:
        fstype: ext4
        dev: "/dev/{{ lvm_vg }}/ledger"

    - name: Write ledger entry in fstab
      ansible.posix.mount:
        path: "{{ validator.ledger_path }}"
        src: "/dev/{{ lvm_vg }}/ledger"
        fstype: ext4
        state: mounted


  when: not lvm_configured.stat.exists
  tags:
    - config.lvm







