---
- name: Ensure group solana exists
  ansible.builtin.group:
    name: "{{ node.solana_user }}"
    state: present

- name: Create user solana
  user:
    name: "{{ node.solana_user }}"
    state: present
    create_home: yes
    shell: /bin/bash
    skeleton: /etc/skel
    force: yes
    groups:
      - "{{ node.solana_user }}"
      - syslog
  tags:
    - config.solana_user

- name: Create secrets dir
  become: yes
  become_user: "{{ node.solana_user }}"
  file:
    path: "{{ validator.secrets_path }}"
    state: directory
    mode: '0700'
  tags:
    - config.solana_user

- name: Create ledger directory
  become: yes
  become_user: "{{ node.solana_user }}"
  file:
    path: "{{ validator.ledger_path }}"
    state: directory
    mode: '0755'
  tags:
    - config.solana_user

- name: Set ledger directory ownership
  file:
    path: "{{ validator.ledger_path }}"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0755
  ignore_errors: True
  tags:
    - config.solana_user


