---

- name: wait for restarting window
  become: yes
  become_user: "{{ validator_user }}"
  shell: solana-validator --ledger {{ ledger_path }} wait-for-restart-window --max-delinquent-stake {{ max_delinquent_stake }} --min-idle-time 2
  async: "{{ wait_for_window_timeout }}"
  poll: 5
  environment:
    PATH: "{{ env_path }}"
  ignore_errors: True
  when: wait_for_window
  tags:
    - validator.manage.restart.wait
