---

- name: Build flat keys path
  set_fact:
    secrets_local_path: "{{ local.secrets_path }}"
  when: local.flat_path
  tags:
    - check.keys

- name: Build non flat keys path
  set_fact:
    secrets_local_path: "{{ local.secrets_path }}/{{ validator.name }}/solana"
  when: not local.flat_path
  tags:
    - check.keys

- name: Check validator-keypair exists locally
  stat:
    path: "{{ secrets_local_path }}/validator-keypair.json"
  connection: local
  become: no
  delegate_to: localhost
  register: validator_keypair_exists
  tags:
    - check.keys

- name: Fail if no validator-keypair exists locally
  fail:
    msg: No validator-keypair exists locally
  when: not validator_keypair_exists.stat.exists
